
   INFO  Running migrations.  

  2025_05_09_030946_create_absensi_table ..........................................................................  
  ⇂ create table `absensi` (`id` bigint unsigned not null auto_increment primary key, `pengguna_id` bigint unsigned not null, `absen_masuk` datetime null, `absen_pulang` datetime null, `pulang_awal` tinyint(1) not null default '0', `alasan_pulang_cepat` varchar(255) null, `lokasi_masuk_latitude` decimal(10, 7) null, `lokasi_masuk_longitude` decimal(10, 7) null, `lokasi_pulang_latitude` decimal(10, 7) null, `lokasi_pulang_longitude` decimal(10, 7) null, `status` enum('Hadir', 'Terlambat', 'Izin', 'Tanpa Keterangan') not null default 'Tanpa Keterangan', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `absensi` add constraint `absensi_pengguna_id_foreign` foreign key (`pengguna_id`) references `pengguna` (`id`) on delete cascade  
  2025_05_09_040935_create_pengajuan_table ........................................................................  
  ⇂ create table `pengajuan` (`id` bigint unsigned not null auto_increment primary key, `nama` varchar(255) not null, `jurusan` varchar(255) not null, `tanggal_masuk` date not null, `tanggal_keluar` date null, `perusahaan_id` bigint unsigned not null, `status` varchar(255) not null default 'Menunggu', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2025_05_14_061446_create_biodata_table ..........................................................................  
  ⇂ create table `biodata` (`id` bigint unsigned not null auto_increment primary key, `nama` varchar(255) not null, `nisn` varchar(255) not null, `nohp` varchar(255) not null, `email` varchar(255) not null, `jenis_kelamin` varchar(255) not null, `tempat_lahir` varchar(255) not null, `tanggal_lahir` date not null, `jurusan` varchar(255) not null, `kelas` varchar(255) not null, `agama` varchar(255) not null, `alamat` text not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `biodata` add unique `biodata_nisn_unique`(`nisn`)  
  ⇂ alter table `biodata` add unique `biodata_email_unique`(`email`)  
  2025_05_16_042731_create_notifikasi_table .......................................................................  
  ⇂ create table `notifikasi` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `message` text not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2025_05_20_072229_create_pengguna_table .........................................................................  
  ⇂ create table `pengguna` (`id` bigint unsigned not null auto_increment primary key, `nama` varchar(255) not null, `email` varchar(255) not null, `password` varchar(255) not null, `role` varchar(255) not null default 'user', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `pengguna` add unique `pengguna_email_unique`(`email`)  
  2025_05_21_075548_create_hari_libur_table .......................................................................  
  ⇂ create table `hari_libur` (`id` bigint unsigned not null auto_increment primary key, `tanggal` date not null, `keterangan` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2025_05_22_082618_create_jadwal_kerja_table .....................................................................  
  ⇂ create table `jadwal_kerja` (`id` bigint unsigned not null auto_increment primary key, `pengguna_id` bigint unsigned not null, `jam_masuk` time not null, `jam_keluar` time not null, `hari_kerja` json not null, `latitude` decimal(10, 7) not null, `longitude` decimal(10, 7) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `jadwal_kerja` add constraint `jadwal_kerja_pengguna_id_foreign` foreign key (`pengguna_id`) references `pengguna` (`id`) on delete cascade  
  2025_05_23_030918_create_pengajuan_table ........................................................................  
  ⇂ create table `pengajuan` (`id` bigint unsigned not null auto_increment primary key, `nama` varchar(255) not null, `instansi` varchar(255) not null, `tanggal` date not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2025_05_26_041324_add_user_id_to_biodata_table ..................................................................  
  ⇂ alter table `biodata` add `user_id` bigint unsigned not null after `id`  
  2025_05_28_034012_create_pembimbings_table ......................................................................  
  ⇂ create table `pembimbings` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  2025_06_02_040759_create_pembimbings_table ......................................................................  
  ⇂ create table `pembimbing` (`id` bigint unsigned not null auto_increment primary key, `nama` varchar(255) not null, `nip` varchar(20) not null, `jurusan` enum('RPL', 'TKJ', 'MM', 'OTKP', 'AKL', 'BDP') not null, `kelas` varchar(50) not null, `no_hp` varchar(15) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  
  ⇂ alter table `pembimbing` add index `pembimbing_nama_nip_jurusan_index`(`nama`, `nip`, `jurusan`)  
  ⇂ alter table `pembimbing` add unique `pembimbing_nip_unique`(`nip`)  
  ⇂ alter table `pembimbing` add unique `pembimbing_email_unique`(`email`)  
  2025_06_04_034604_create_biodata_table ..........................................................................  
  ⇂ create table `biodata` (`id` bigint unsigned not null auto_increment primary key, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  

